# 1142_DS_Lab4 Pandas 數據分析套件

In [1]:
import pandas as pd
import numpy as np
import requests

# Pandas 主要資料結構介紹 - Series

### Series 為附帶index的一維numpy array(ndarray)，index是可重複的。
##### Series API Reference: https://pandas.pydata.org/pandas-docs/stable/reference/series.html

#### Series 可儲存不同類別的資料

In [2]:
s = pd.Series(['value1', 1.0, 3])
s

0    value1
1       1.0
2         3
dtype: object

In [3]:
s = pd.Series([4, 7, -5, 3])
s

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
s.values

array([ 4,  7, -5,  3])

In [5]:
s = pd.Series(['Value1', 1.0, 3])
s

0    Value1
1       1.0
2         3
dtype: object

In [6]:
s[0:2] # Get value with row index

0    Value1
1       1.0
dtype: object

## Operation

#### 兩Series的Operation(+,-,/,..)會根據相同的index計算，長度不需相同。
#### 計算時只處理index在兩Series index交集的值，若不在交集中則為NaN

In [7]:
a = pd.Series([1,2,3,4,5], index=[0,1,2,3,4])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
b = pd.Series([1,2,3,4,5],index=[1,2,3,4,5])
b

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [9]:
a+b

0    NaN
1    3.0
2    5.0
3    7.0
4    9.0
5    NaN
dtype: float64

#### 若是出現重複的index時則會將所有組合都計算。

#### 下面的例子中 Series a 中有兩個 index 0，因此0在結果(a+b)的index中也出現了兩次，分別是2(1+1)和3(1+2)

In [10]:
a = pd.Series([1,2,3], index=[0,0,1])
b = pd.Series([1,2,3], index=[0,1,2])
print(a)
print(b)
print(a+b)

0    1
0    2
1    3
dtype: int64
0    1
1    2
2    3
dtype: int64
0    2.0
0    3.0
1    5.0
2    NaN
dtype: float64

#### 若是inedx在Series a 和 b中都重複出現時，則會如下所示。
#### index 0在 a和b中各出現了兩次，因此結果便有4個index為0的值，分別為2(1+1)、4(1+3)、3(2+1)、5(2+3)

In [11]:
a = pd.Series([1,2,3], index=[0,0,1])
b = pd.Series([1,2,3], index=[0,1,0])
print(a+b)

0    2
0    4
0    3
0    5
1    5
dtype: int64

# Pandas 主要資料結構介紹 - DataFrame
### dataframe 為二維的、大小可更動的表格資料，可視為dictionary-like的Series。
##### DataFrame API  Reference: https://pandas.pydata.org/pandas-docs/stable/reference/frame.html

In [12]:
df = pd.DataFrame({'column1':[0,1,2,3], 'column2':[4,5,6,7]}, index=[0,1,2,3])
df

   column1  column2
0        0        4
1        1        5
2        2        6
3        3        7

In [13]:
df['column2']

0    4
1    5
2    6
3    7
Name: column2, dtype: int64

In [14]:
df['column2'].isin([5])  # isin() 可以判斷DataFrame、Series 以及索引是否包含傳入的指定值，返回True表示有包含。

0    False
1     True
2    False
3    False
Name: column2, dtype: bool

In [15]:
df.column2.isin(['5'])

0    False
1    False
2    False
3    False
Name: column2, dtype: bool

In [15]:
df.drop??

Signature:
df.drop(
    labels: 'IndexLabel | None' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | None' = None,
    columns: 'IndexLabel | None' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise',
) -> 'DataFrame | None'
Source:
    def drop(
        self,
        labels: IndexLabel | None = None,
        *,
        axis: Axis = 0,
        index: IndexLabel | None = None,
        columns: IndexLabel | None = None,
        level: Level | None = None,
        inplace: bool = False,
        errors: IgnoreRaise = "raise",
    ) -> DataFrame | None:
        """
        Drop specified labels from rows or columns.

        Remove rows or columns by specifying label names and corresponding
        axis, or by directly specifying index or column names. When using a
        multi-index, labels on different levels can be removed by specifying
        the level. See the :ref:`user guide <advanced.shown_levels>`
        for more information about the now unused levels.

        Parameters
        ----------
        labels : single label or list-like
            Index or column labels to drop. A tuple will be used as a single
            label and not treated as a list-like.
        axis : {0 or 'index', 1 or 'columns'}, default 0
            Whether to drop labels from the index (0 or 'index') or
            columns (1 or 'columns').
        index : single label or list-like
            Alternative to specifying axis (``labels, axis=0``
            is equivalent to ``index=labels``).
        columns : single label or list-like
            Alternative to specifying axis (``labels, axis=1``
            is equivalent to ``columns=labels``).
        level : int or level name, optional
            For MultiIndex, level from which the labels will be removed.
        inplace : bool, default False
            If False, return a copy. Otherwise, do operation
            in place and return None.
        errors : {'ignore', 'raise'}, default 'raise'
            If 'ignore', suppress error and only existing labels are
            dropped.

        Returns
        -------
        DataFrame or None
            Returns DataFrame or None DataFrame with the specified
            index or column labels removed or None if inplace=True.

        Raises
        ------
        KeyError
            If any of the labels is not found in the selected axis.

        See Also
        --------
        DataFrame.loc : Label-location based indexer for selection by label.
        DataFrame.dropna : Return DataFrame with labels on given axis omitted
            where (all or any) data are missing.
        DataFrame.drop_duplicates : Return DataFrame with duplicate rows
            removed, optionally only considering certain columns.
        Series.drop : Return Series with specified index labels removed.

        Examples
        --------
        >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
        ...                   columns=['A', 'B', 'C', 'D'])
        >>> df
           A  B   C   D
        0  0  1   2   3
        1  4  5   6   7
        2  8  9  10  11

        Drop columns

        >>> df.drop(['B', 'C'], axis=1)
           A   D
        0  0   3
        1  4   7
        2  8  11

        >>> df.drop(columns=['B', 'C'])
           A   D
        0  0   3
        1  4   7
        2  8  11

        Drop a row by index

        >>> df.drop([0, 1])
           A  B   C   D
        2  8  9  10  11

        Drop columns and/or rows of MultiIndex DataFrame

        >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
        ...                              ['speed', 'weight', 'length']],
        ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
        ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
        >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
        ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
        ...                         [250, 150], [1.5, 0.8], [320, 250],
        ...                         [1, 0.8], [0.3, 0.2]])
        >>> df
                        big     small
        llama   speed   45.0    30.0
                weight  200.0   100.0
                length  1.5     1.0
        cow     speed   30.0    20.0
                weight  250.0   150.0
                length  1.5     0.8
        falcon  speed   320.0   250.0
                weight  1.0     0.8
                length  0.3     0.2

        Drop a specific index combination from the MultiIndex
        DataFrame, i.e., drop the combination ``'falcon'`` and
        ``'weight'``, which deletes only the corresponding row

        >>> df.drop(index=('falcon', 'weight'))
                        big     small
        llama   speed   45.0    30.0
                weight  200.0   100.0
                length  1.5     1.0
        cow     speed   30.0    20.0
                weight  250.0   150.0
                length  1.5     0.8
        falcon  speed   320.0   250.0
                length  0.3     0.2

        >>> df.drop(index='cow', columns='small')
                        big
        llama   speed   45.0
                weight  200.0
                length  1.5
        falcon  speed   320.0
                weight  1.0
                length  0.3

        >>> df.drop(index='length', level=1)
                        big     small
        llama   speed   45.0    30.0
                weight  200.0   100.0
        cow     speed   30.0    20.0
                weight  250.0   150.0
        falcon  speed   320.0   250.0
                weight  1.0     0.8
        """
        return super().drop(
            labels=labels,
            axis=axis,
            index=index,
            columns=columns,
            level=level,
            inplace=inplace,
            errors=errors,
        )
File:      c:\users\twp\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [17]:
df.drop(['column2'],axis=1) # drop() 删除一行或一列

   column1
0        0
1        1
2        2
3        3

In [16]:
df = pd.DataFrame({'column1':[0,1,2,3], 'column2':[4,5,6,7]}, index=[1,2,3,4])#若是沒有指定index，則index從0開始
df

   column1  column2
1        0        4
2        1        5
3        2        6
4        3        7

### 如同Series，可在同一Data Frame中儲存不同型別的資料。

In [17]:
df = pd.DataFrame({'column1':[0, 1, 2, 3], 'column2':[4.0, 'value5', 6, 7]}, index=[1, 2, 3, 4])
df

   column1 column2
1        0     4.0
2        1  value5
3        2       6
4        3       7

In [18]:
df['column1']

1    0
2    1
3    2
4    3
Name: column1, dtype: int64

In [19]:
df['column2']

1       4.0
2    value5
3         6
4         7
Name: column2, dtype: object

## Operation
#### 運算邏輯大致與Series相同，計算時以行、列兩者index皆相同者計算。

#### 兩者計算時只有column name 為'column1'且row index為[1,2,3]的值存在於兩者交集之中，
#### 因此結果為 1(0+1)、3(1+2)、5(2+3)，其餘則為空值。

In [20]:
df1 = pd.DataFrame({'column1':[0,1,2,3], 'column2':[4,5,6,7]}, index=[1,2,3,4])
df2 = pd.DataFrame({'column1':[0,1,2,3], 'column3':[4,5,6,7]})
df1

   column1  column2
1        0        4
2        1        5
3        2        6
4        3        7

In [21]:
df2

   column1  column3
0        0        4
1        1        5
2        2        6
3        3        7

In [26]:
df1+df2

   column1  column2  column3
0      NaN      NaN      NaN
1      1.0      NaN      NaN
2      3.0      NaN      NaN
3      5.0      NaN      NaN
4      NaN      NaN      NaN

## index重複時運算處理

### 若是inedx重複出現時，分為兩種情況。

### 1.重複出現次數一致時

In [22]:
df1 = pd.DataFrame({'column1':[0,1,2,3], 'column2':[4,5,6,7]}, index=[1,2,3,3])
df1

   column1  column2
1        0        4
2        1        5
3        2        6
3        3        7

In [24]:
df2 = pd.DataFrame({'column1':[0,1,2,3], 'column2':[4,5,6,7]}, index=[1,2,3,3])
df2

   column1  column2
1        0        4
2        1        5
3        2        6
3        3        7

#### 此時不像Series出現4筆資料，而是根據位置只計算兩組資料。

In [25]:
df1+df2

   column1  column2
1        0        8
2        2       10
3        4       12
3        6       14

### 2.重複出現次數不一致

In [26]:
df1 = pd.DataFrame({'column1':[0,1,2,3], 'column2':[4,5,6,7]}, index=[1,2,3,3])
df1

   column1  column2
1        0        4
2        1        5
3        2        6
3        3        7

In [27]:
df2 = pd.DataFrame({'column1':[0,1,2,3], 'column2':[4,5,6,7]}, index=[1,3,3,3])
df2

   column1  column2
1        0        4
3        1        5
3        2        6
3        3        7

#### 此時則會計算所有的組合結果

In [28]:
df1+df2 #df2中並沒有 row '2' 因此為空值

   column1  column2
1      0.0      8.0
2      NaN      NaN
3      3.0     11.0
3      4.0     12.0
3      5.0     13.0
3      4.0     12.0
3      5.0     13.0
3      6.0     14.0

# 資料處理
### 以上一章節中使用的股市資料示範如何利用Pandas進行資料篩選以及處理。

### 股市資料

In [18]:
date = "20260320"
url = f'https://www.twse.com.tw/exchangeReport/MI_INDEX?response=json&date={date}&type=ALLBUT0999'
response = requests.get(url)
response_json = response.json()
# 找到每日收盤行情的數據
stock_data = []
stock_fields = []
for table in response_json['tables']:
    if "每日收盤行情" in table['title']:  # 確保是股票成交資訊
        stock_data = table['data']  # 股票成交數據
        stock_fields = table['fields']  # 欄位名稱
        break

# 確保有數據才建立 DataFrame
if stock_data and stock_fields:
    stock = pd.DataFrame(stock_data, columns=stock_fields)
else:
    print("Error: 未找到每日收盤行情的數據")

In [31]:
stock.to_csv('stock_20260320.csv', index=False)

In [32]:
# 用上次閜仔的資料，使用pd.read_csv(filepath)即可
pd.read_csv('stock_20260320.csv').head()

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,"72,638,922","101,109","5,517,624,557",76.20,76.40,75.50,75.90,<p style= color:green>-</p>,0.10,75.90,564,75.95,45,0.00
1,0051,元大中型100,"116,481","1,155","13,077,989",112.80,113.20,110.90,111.90,<p style= color:green>-</p>,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,"29,899,678","24,990","1,356,032,270",45.65,45.74,45.10,45.26,<p style= color:green>-</p>,0.28,45.25,276,45.26,43,0.00
3,0053,元大電子,"31,694",218,"5,422,510",170.40,172.05,169.15,171.70,<p> </p>,0.00,169.60,50,171.70,52,0.00
4,0055,元大MSCI金融,"89,324",408,"2,883,899",32.21,32.40,32.15,32.36,<p style= color:red>+</p>,0.15,32.37,1,32.40,1,0.00

In [19]:
stock.head()

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,"72,638,922","101,109","5,517,624,557",76.20,76.40,75.50,75.90,<p style= color:green>-</p>,0.10,75.90,564,75.95,45,0.00
1,0051,元大中型100,"116,481","1,155","13,077,989",112.80,113.20,110.90,111.90,<p style= color:green>-</p>,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,"29,899,678","24,990","1,356,032,270",45.65,45.74,45.10,45.26,<p style= color:green>-</p>,0.28,45.25,276,45.26,43,0.00
3,0053,元大電子,"31,694",218,"5,422,510",170.40,172.05,169.15,171.70,<p> </p>,0.00,169.60,50,171.70,52,0.00
4,0055,元大MSCI金融,"89,324",408,"2,883,899",32.21,32.40,32.15,32.36,<p style= color:red>+</p>,0.15,32.37,1,32.40,1,0.00

## 資料篩選 - slice
#### 將第0到第2(3-1)筆資料取出

In [20]:
stock[0:3]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,"72,638,922","101,109","5,517,624,557",76.20,76.40,75.50,75.90,<p style= color:green>-</p>,0.10,75.90,564,75.95,45,0.00
1,0051,元大中型100,"116,481","1,155","13,077,989",112.80,113.20,110.90,111.90,<p style= color:green>-</p>,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,"29,899,678","24,990","1,356,032,270",45.65,45.74,45.10,45.26,<p style= color:green>-</p>,0.28,45.25,276,45.26,43,0.00

### Select by location - iloc、iat
#### 取出"位置"在第二筆的資料
#### iloc[ ] 含頭不含尾

In [35]:
stock.iloc[1] #start from 0

證券代號                              0051
證券名稱                           元大中型100
成交股數                           116,481
成交筆數                             1,155
成交金額                        13,077,989
開盤價                             112.80
最高價                             113.20
最低價                             110.90
收盤價                             111.90
漲跌(+/-)    <p style= color:green>-</p>
漲跌價差                              1.40
最後揭示買價                          111.65
最後揭示買量                               4
最後揭示賣價                          112.75
最後揭示賣量                              50
本益比                               0.00
Name: 1, dtype: object

In [26]:
stock.iloc[1:4]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
1,0051,元大中型100,"116,481","1,155","13,077,989",112.80,113.20,110.90,111.90,<p style= color:green>-</p>,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,"29,899,678","24,990","1,356,032,270",45.65,45.74,45.10,45.26,<p style= color:green>-</p>,0.28,45.25,276,45.26,43,0.00
3,0053,元大電子,"31,694",218,"5,422,510",170.40,172.05,169.15,171.70,<p> </p>,0.00,169.60,50,171.70,52,0.00

#### 取出"位置"在第二筆第二行的資料
#### iat[ , ] 只能訪問單個元素

In [29]:
stock.iat[1,1] #start from 0

'元大中型100'

### Slice by index - loc
#### 取出row index為 0到2的值
#### loc[ ] 含頭也含尾

In [38]:
stock.loc[0:2]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,"72,638,922","101,109","5,517,624,557",76.20,76.40,75.50,75.90,<p style= color:green>-</p>,0.10,75.90,564,75.95,45,0.00
1,0051,元大中型100,"116,481","1,155","13,077,989",112.80,113.20,110.90,111.90,<p style= color:green>-</p>,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,"29,899,678","24,990","1,356,032,270",45.65,45.74,45.10,45.26,<p style= color:green>-</p>,0.28,45.25,276,45.26,43,0.00

取出row index從0到3且column index從"開盤價"到"收盤價"的值

In [39]:
stock.loc[0:3, "開盤價":"收盤價"]

      開盤價     最高價     最低價     收盤價
0   76.20   76.40   75.50   75.90
1  112.80  113.20  110.90  111.90
2   45.65   45.74   45.10   45.26
3  170.40  172.05  169.15  171.70

### 資料篩選 - Mask
#### 透過 loc 以Mask的方式擷取所需的資料

取出row index小於5的資料

In [40]:
stock.loc[stock.index < 5]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,"72,638,922","101,109","5,517,624,557",76.20,76.40,75.50,75.90,<p style= color:green>-</p>,0.10,75.90,564,75.95,45,0.00
1,0051,元大中型100,"116,481","1,155","13,077,989",112.80,113.20,110.90,111.90,<p style= color:green>-</p>,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,"29,899,678","24,990","1,356,032,270",45.65,45.74,45.10,45.26,<p style= color:green>-</p>,0.28,45.25,276,45.26,43,0.00
3,0053,元大電子,"31,694",218,"5,422,510",170.40,172.05,169.15,171.70,<p> </p>,0.00,169.60,50,171.70,52,0.00
4,0055,元大MSCI金融,"89,324",408,"2,883,899",32.21,32.40,32.15,32.36,<p style= color:red>+</p>,0.15,32.37,1,32.40,1,0.00

複數條件篩選 - row index 大於5且小於10的資料

In [41]:
stock.loc[(stock.index > 5) & (stock.index < 10)]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
6,0057,富邦摩台,"12,587",123,"2,840,863",225.70,226.65,225.25,225.30,<p style= color:red>+</p>,0.60,225.30,1,225.40,1,0.00
7,0061,元大寶滬深,"411,538",212,"9,653,645",23.44,23.56,23.30,23.37,<p style= color:green>-</p>,0.07,23.37,65,23.45,74,0.00
8,006203,元大MSCI台灣,"6,859",99,"947,932",138.70,138.70,137.90,137.90,<p style= color:green>-</p>,0.95,137.30,1,137.70,1,0.00
9,006204,永豐臺灣加權,"15,129",110,"2,596,494",171.00,171.80,171.00,171.05,<p style= color:green>-</p>,1.20,171.20,1,171.90,1,0.00

## 型別轉換
#### 在資料中"最高價"被儲存為字串，我們可以將其轉換為數值方便計算。

In [42]:
print(type(stock.最高價[0]))
stock.最高價[0]

<class 'str'>

'76.40'

#### 使用astype將字串轉為float

In [43]:
stock.最高價.head().astype("float")

0     76.40
1    113.20
2     45.74
3    172.05
4     32.40
Name: 最高價, dtype: float64

##### could not convert string to float: '--'
#### 在轉換的過程中出現無法解析的字串時便會發生錯誤

In [44]:
stock.最高價.astype("float")

ValueError: could not convert string to float: '--'

### 使用to_numeric進行轉換，errors參數可指定解析錯誤時的處理，
#### 　　raise:  中斷執行，拋出例外。
#### 　　ignore: 不進行轉換，回傳原值。
#### 　　corece: 回傳 NaN

In [45]:
replace_map = {",":"", "--":np.nan}
stock = stock.replace(replace_map, regex=True)
stock.head()

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,72638922,101109,5517624557,76.20,76.40,75.50,75.90,<p style= color:green>-</p>,0.10,75.90,564,75.95,45,0.00
1,0051,元大中型100,116481,1155,13077989,112.80,113.20,110.90,111.90,<p style= color:green>-</p>,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,29899678,24990,1356032270,45.65,45.74,45.10,45.26,<p style= color:green>-</p>,0.28,45.25,276,45.26,43,0.00
3,0053,元大電子,31694,218,5422510,170.40,172.05,169.15,171.70,<p> </p>,0.00,169.60,50,171.70,52,0.00
4,0055,元大MSCI金融,89324,408,2883899,32.21,32.40,32.15,32.36,<p style= color:red>+</p>,0.15,32.37,1,32.40,1,0.00

In [86]:
stock.最高價 = pd.to_numeric(stock.最高價, errors='coerce', downcast='float')

In [46]:
stock.最高價.isnull()  # 判斷缺失值

0       False
1       False
2       False
3       False
4       False
        ...
1338    False
1339    False
1340    False
1341    False
1342    False
Name: 最高價, Length: 1343, dtype: bool

In [47]:
stock.最高價[stock.最高價.isnull()]#查看所有轉換後為NaN的值

14      NaN
77      NaN
223     NaN
224     NaN
236     NaN
744     NaN
1123    NaN
1206    NaN
1289    NaN
Name: 最高價, dtype: object

## 使用describe快速了解資料
#### describe根據資料型別，計算簡單的統計結果。

In [50]:
stock.最高價.describe()

count      1334
unique     1033
top       40.00
freq          5
Name: 最高價, dtype: object

# 資料取代
在"漲跌(+/-)"中資料被儲存為HTML格式，我們將其取代為boolean格式以方便計算。

### 透過使用value_counts查看有多少種不同的值以及其出現次數。

##### *空值將不會出現以及計算出現次數。*

In [51]:
stock['漲跌(+/-)'].value_counts()

漲跌(+/-)
<p style= color:green>-</p>    666
<p style= color:red>+</p>      558
<p> </p>                       108
<p>X</p>                        11
Name: count, dtype: int64

### 取代資料中的 + 資料為True
### 使用 replace() 進行批次替換

In [52]:
stock['漲跌(+/-)'].replace('<p style= color:red>+</p>', True).head(10)

0    <p style= color:green>-</p>
1    <p style= color:green>-</p>
2    <p style= color:green>-</p>
3                       <p> </p>
4                           True
5    <p style= color:green>-</p>
6                           True
7    <p style= color:green>-</p>
8    <p style= color:green>-</p>
9    <p style= color:green>-</p>
Name: 漲跌(+/-), dtype: object

### 也可一次指定多筆取代操作

In [53]:
replace_map = {"<p style= color:red>+</p>":True, "<p style= color:green>-</p>":False}
stock['漲跌(+/-)'].replace(replace_map).value_counts()

漲跌(+/-)
False       666
True        558
<p> </p>    108
<p>X</p>     11
Name: count, dtype: int64

## 使用map取代資料
### replace只將所有符合的字串取代
### 可利用map將其餘值轉換為NaN方便計算

In [54]:
replace_map = {"<p style= color:red>+</p>":True, "<p style= color:green>-</p>":False, True:True, False:False}
#keep True as True, False as False

stock['漲跌(+/-)'] = stock['漲跌(+/-)'].map(replace_map)
stock['漲跌(+/-)'].value_counts() #not include nan

漲跌(+/-)
False    666
True     558
Name: count, dtype: int64

### 使用isnull計算空值數量

In [55]:
stock['漲跌(+/-)'].isnull().sum()

np.int64(119)

### 使用isnull構成mask查詢'漲跌(+/-)'為空值的資料，若是想要查詢'漲跌(+/-)'非空值的資料可使用notnull。

In [56]:
stock[stock['漲跌(+/-)'].isnull()]

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
3,0053,元大電子,31694,218,5422510,170.40,172.05,169.15,171.70,NaN,0.00,169.60,50,171.70,52,0.00
14,00625K,富邦上証+R,0,0,0,NaN,NaN,NaN,NaN,NaN,0.00,8.62,5,8.72,5,0.00
18,00634R,富邦上証反1,325900,13,1068453,3.22,3.29,3.22,3.29,NaN,0.00,3.27,200,3.29,383,0.00
26,00641R,富邦日本反1,2261600,95,9683290,4.29,4.29,4.25,4.28,NaN,0.00,4.27,463,4.28,17,0.00
29,00643K,群益深証中小+R,1000,1,3910,3.91,3.91,3.91,3.91,NaN,0.00,3.91,2,3.95,1,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1289,8488,吉源-KY,1,1,10,NaN,NaN,NaN,NaN,NaN,0.00,9.70,1,9.97,4,0.00
1301,911868,同方友友-DR,577001,53,726901,1.27,1.27,1.25,1.27,NaN,0.00,1.26,15,1.27,161,0.00
1306,9904,寶成,13310981,4851,380733766,28.60,28.75,28.30,28.60,NaN,0.00,28.55,557,28.60,43,6.98
1307,9905,大華,38608,53,808451,20.90,21.00,20.90,21.00,NaN,0.00,20.90,12,21.00,13,16.15
1336,9942,茂順,55631,121,6426784,115.50,116.00,115.00,115.50,NaN,0.00,115.00,47,116.00,9,14.15

In [57]:
stock['漲跌(+/-)'].notnull().sum()

np.int64(1224)

In [58]:
stock[stock['漲跌(+/-)'].notnull()].head(10)

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,72638922,101109,5517624557,76.20,76.40,75.50,75.90,False,0.10,75.90,564,75.95,45,0.00
1,0051,元大中型100,116481,1155,13077989,112.80,113.20,110.90,111.90,False,1.40,111.65,4,112.75,50,0.00
2,0052,富邦科技,29899678,24990,1356032270,45.65,45.74,45.10,45.26,False,0.28,45.25,276,45.26,43,0.00
4,0055,元大MSCI金融,89324,408,2883899,32.21,32.40,32.15,32.36,True,0.15,32.37,1,32.40,1,0.00
5,0056,元大高股息,37631551,25543,1460272826,38.88,38.98,38.56,38.77,False,0.11,38.77,25,38.78,78,0.00
6,0057,富邦摩台,12587,123,2840863,225.70,226.65,225.25,225.30,True,0.60,225.30,1,225.40,1,0.00
7,0061,元大寶滬深,411538,212,9653645,23.44,23.56,23.30,23.37,False,0.07,23.37,65,23.45,74,0.00
8,006203,元大MSCI台灣,6859,99,947932,138.70,138.70,137.90,137.90,False,0.95,137.30,1,137.70,1,0.00
9,006204,永豐臺灣加權,15129,110,2596494,171.00,171.80,171.00,171.05,False,1.20,171.20,1,171.90,1,0.00
10,006205,富邦上証,707995,223,28232379,39.89,40.02,39.70,39.81,False,0.18,39.80,1,39.83,178,0.00

## apply介紹
### 使用apply將函式套用在所有資料上
#### 上表中我們發現資料集中還是有很多不能直接轉換為數值的字串( 例如超過1000元有含有"',"的符號  1,000 )
#### 透過apply一次將所有可轉為數值的資料進行轉換。

In [59]:
data = stock.loc[:, "成交股數" : "收盤價"]
data.head(10)

       成交股數    成交筆數        成交金額     開盤價     最高價     最低價     收盤價
0  72638922  101109  5517624557   76.20   76.40   75.50   75.90
1    116481    1155    13077989  112.80  113.20  110.90  111.90
2  29899678   24990  1356032270   45.65   45.74   45.10   45.26
3     31694     218     5422510  170.40  172.05  169.15  171.70
4     89324     408     2883899   32.21   32.40   32.15   32.36
5  37631551   25543  1460272826   38.88   38.98   38.56   38.77
6     12587     123     2840863  225.70  226.65  225.25  225.30
7    411538     212     9653645   23.44   23.56   23.30   23.37
8      6859      99      947932  138.70  138.70  137.90  137.90
9     15129     110     2596494  171.00  171.80  171.00  171.05

#### replace 參數regex=true 使用正則表達式搜尋並且取代

In [60]:
replace_map = {",":"", "--":np.nan}
data = data.replace(replace_map, regex=True)
data.head()

       成交股數    成交筆數        成交金額     開盤價     最高價     最低價     收盤價
0  72638922  101109  5517624557   76.20   76.40   75.50   75.90
1    116481    1155    13077989  112.80  113.20  110.90  111.90
2  29899678   24990  1356032270   45.65   45.74   45.10   45.26
3     31694     218     5422510  170.40  172.05  169.15  171.70
4     89324     408     2883899   32.21   32.40   32.15   32.36

In [99]:
data = data.apply(pd.to_numeric, errors='coerce') #errors為to_numeric之參數
data.head()

      成交股數   成交筆數        成交金額     開盤價         最高價     最低價     收盤價
0  9097283  16607  1795160598  196.50  197.949997  195.90  197.95
1    67833    395     5452970   79.70   80.599998   79.70   80.50
2   821280   1355   162442505  196.40  198.100006  196.25  197.95
3    12420    100     1308849  104.80  105.800003  104.80  105.70
4   125949    190     3652950   28.97   29.030001   28.94   29.02

###### 練習: 請問2026/3/21日台灣股市收盤價每一股超過1000元的股票有幾家公司? 這幾家每股超過1000元的平均收盤價是多少? 目前股王是哪一家公司?